kind : dockerhub
imagenames:
  - imagename: gtp7473/image1
    gitrepos:
      - gitrepo: https://github.com/gtp7473/chart2.git
      - gitrepo: https://github.com/gtp7473/chart1.git
  - imagename: gtp7473/image2
    gitrepos:
      - gitrepo: https://github.com/gtp7473/chart1.git
      - gitrepo: https://github.com/gtp7473/chart3.git
